project_id = "fttijdskbsvjvnszutzh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:5500"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.payment-webhook]
verify_jwt = false

[functions.n8n-webhook-handler]
verify_jwt = true

[functions.n8n-custom-webhook]
verify_jwt = false

[functions.n8n-chat-integration]
verify_jwt = false

[functions.crystal-analytics]
verify_jwt = true

[functions.crystal-chat]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false