// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttijdskbsvjvnszutzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dGlqZHNrYnN2anZuc3p1dHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDgwODcsImV4cCI6MjA3MzQ4NDA4N30.9PIfBGX3z_h7bhK9s7Nd9ccI9pJvvvKxdmNnQ1-UKaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});